global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape weather consumer metrics
  - job_name: 'weather-consumer'
    static_configs:
      - targets: ['weather-consumer:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Scrape Alert Manager
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
